# DATA LOADER SETTINGS
dataloading:
  path_to_data: "data/raw/"
  train_path: "train_FD"
  test_path: "test_FD"
  RUL_path: "RUL_FD"

# PREPROCESSING SETTINGS
preprocessing:
  conditions: ["MathxHard"]
  partition_size: 250
  fixed_size: 11000

# ARCHITECTURE SETTINGS
architecture:
  latent_dims: 8
  beta: 0.01
  dropout_rate: 0.0

# FITTING SETTINGS
fitting:
  epochs: 128
  batch_size: 4
