# PATHS SETTINGS FROM ROOT
paths:
  model_dir: "./models/"
  processed_data_dir: "./data/processed/"
  prediction_dir: "./data/predictions/"
  document_dir: "./docs/"
  plot_dir: "./images/"

# DATA LOADER SETTINGS
dataloading:
  data_dir: "data/raw/"
  sets:
    - number: 1
      train: "train_FD001.txt"
      test: "test_FD001.txt"
      RUL: "RUL_FD001.txt"
      min_cycle: 31
    - number: 2
      train: "train_FD002.txt"
      test: "test_FD002.txt"
      RUL: "RUL_FD002.txt"
      min_cycle: 21
    - number: 3
      train: "train_FD003.txt"
      test: "test_FD003.txt"
      RUL: "RUL_FD003.txt"
      min_cycle: 38
    - number: 4
      train: "train_FD004.txt"
      test: "test_FD004.txt"
      RUL: "RUL_FD004.txt"
      min_cycle: 19
  index: &index
    - UnitNumber
    - Cycle
  features:
    operational_settings: &operational_settings
      - Operation Setting 1
      - Operation Setting 2
      - Operation Setting 3
    sensor_measure: &sensor_measure
      - Sensor Measure 1
      - Sensor Measure 2
      - Sensor Measure 3
      - Sensor Measure 4
      - Sensor Measure 5
      - Sensor Measure 6
      - Sensor Measure 7
      - Sensor Measure 8
      - Sensor Measure 9
      - Sensor Measure 10
      - Sensor Measure 11
      - Sensor Measure 12
      - Sensor Measure 13
      - Sensor Measure 14
      - Sensor Measure 15
      - Sensor Measure 16
      - Sensor Measure 17
      - Sensor Measure 18
      - Sensor Measure 19
      - Sensor Measure 20
      - Sensor Measure 21
  target: "RUL"
  columns:
    - *index
    - *operational_settings
    - *sensor_measure

# PREPROCESSING SETTINGS
preprocessing:
  min_window_size: 10
  max_window_size: 10
  max_RUL: 130
  feature_extraction_mode:
    quantile:
      - q: 0.1
      - q: 0.5
      - q: 0.9
    number_peaks:
      - n: 1
      - n: 5
    autocorrelation:
      - lag: 1
      - lag: 2
      - lag: 3
    partial_autocorrelation:
      - lag: 1
      - lag: 2
      - lag: 3
    linear_trend:
      - attr: slope
      - attr: intercept
    agg_linear_trend:
      - attr: slope
        chunk_len: 5
        f_agg: mean
      - attr: slope
        chunk_len: 5
        f_agg: var
      - attr: slope
        chunk_len: 10
        f_agg: mean
      - attr: slope
        chunk_len: 10
        f_agg: var
      - attr: intercept
        chunk_len: 5
        f_agg: mean
      - attr: intercept
        chunk_len: 5
        f_agg: var
      - attr: intercept
        chunk_len: 10
        f_agg: mean
      - attr: intercept
        chunk_len: 10
        f_agg: var
    fft_coefficient:
      - coeff: 0
        attr: real
      - coeff: 1
        attr: real
      - coeff: 2
        attr: real
      - coeff: 0
        attr: imag
      - coeff: 1
        attr: imag
      - coeff: 2
        attr: imag
    fft_aggregated:
      - aggtype: centroid
      - aggtype: variance
    approximate_entropy:
      - m: 2
        r: 0.1
      - m: 2
        r: 0.5
    lempel_ziv_complexity:
      - bins: 5
    energy_ratio_by_chunks:
      - num_segments: 10
        segment_focus: 0
      - num_segments: 10
        segment_focus: 1
      - num_segments: 10
        segment_focus: 2
      - num_segments: 10
        segment_focus: 3
      - num_segments: 10
        segment_focus: 4
    count_above:
      - t: 0
    count_below:
      - t: 0
    binned_entropy:
      - max_bins: 10
    # minimal features
    maximum: []
    minimum: []
    mean: []
    median: []
    standard_deviation: []
    variance: []
    skewness: []
    kurtosis: []

# ARCHITECTURE SETTINGS
architecture:
  latent_dims: 8
  beta: 0.01
  dropout_rate: 0.0
  selected_features: ["MathxHard"]

# FITTING SETTINGS
fitting:
  epochs: 128
  batch_size: 4
